### ISSUE TITLE
YAML形式読み書きの追加

### ISSUE THREAD

**Issue by cocco84** [stuncloud/UWSCR#242]
### 概要

YAML形式も構造体として扱いたい。

### 理由

UWSC/UWSCRの設定ファイルと言えば、やはりINI形式が一般的かと思います。
ただし、プログラムの配布を前提にユーザー自身で設定ファイルを編集・更新してもらう場合、
INI形式では改行の扱いや記述制限などの問題があります。

とくに、ChatGPTのプロンプト文のように複数行にわたるテキストをそのまま記述させたいケースでは、
INIでは限界があり、現在はやむを得ず（親和性が高いというのもありますが）
Excelファイルなどを無理やり設定ファイルとして扱っている状況です。

もちろん、UWSCRではJSONにも対応はしていただいていますが、
利用ユーザーが非エンジニアである場合、
括弧やカンマ、エスケープ処理の必要性から、JSONの編集ハードルが高いと感じています。

その点、YAML形式であれば：

・改行を含む文章の記述がしやすい（| 構文など）
・コメントも書けるため、設定内容の補足が可能
・視覚的にも読みやすく、ミスも起きにくい
　※もちろん、複雑な構造にしなければ、という前提ですが

といった利点があり、ユーザー側での自由な編集や差し替えがより
スムーズに行えるのではないかと思っています。

`readini `的な扱いではなく、`FromJson` や `ToJson` のような構造体ベースの方法で
YAMLも読み書きできるようになると嬉しいのですが、いかがでしょうか？

また、エスケープ処理を含んだJSONとYAMLの相互変換も実装があるとなお助かります。

### 実装例

```Stylus

```

**Comment by stuncloud** [comment]
良いですね

yamlシリアライザ/デシリアライザも下地がserdeのものがあるので、それを使うことでjsonと同じように実装できると思います
いずれも下地がserdeであるので相互互換も容易いと思われ、jsonファイルを読み込んでyamlファイルを書き出すといったことも可能であるはずです

jsonのようなリテラル表記を考慮しなければすぐに実装できそうなので、近い内に調べてみます

----

ちなみに設定ファイルも今はjsonで、まあまあ書きにくいということから新フォーマットの試作を進めていたりします
新フォーマットはtomlですが、json schema対応エディタによる入力支援も含めてうまく動作しています
いずれはこちらに切り替えていきたいですね

**Comment by stuncloud** [comment]
- toyaml
- fromyaml

を実装

```stylus
j = @{
    "hoge": {
        "foo": 1,
        "bar": [100, 200, 300]
    },
    "fuga": [
        {
            "baz": 1,
            "qux": 11
        },
        {
            "baz": 2,
            "qux": 22
        },
        {
            "baz": 3,
            "qux": 33
        }
    ]
}@

print tojson(j)
print toyaml(j)
```

出力
```
{"hoge":{"foo":1,"bar":[100,200,300]},"fuga":[{"baz":1,"qux":11},{"baz":2,"qux":22},{"baz":3,"qux":33}]}
hoge:
  foo: 1.0
  bar:
  - 100.0
  - 200.0
  - 300.0
fuga:
- baz: 1.0
  qux: 11.0
- baz: 2.0
  qux: 22.0
- baz: 3.0
  qux: 33.0
```

- json由来のUObjectをtoyaml→yaml文字列
- yaml由来のUObjectをtojson→json文字列

のように相互互換あり
